
package com.yado.cxf;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICustomerService", targetNamespace = "http://service.yado.com/")
@XmlSeeAlso({
   // ObjectFactory.class
})
public interface ICustomerService {


    /**
     * 
     * @return
     *     returns java.util.List<com.yado.cxf.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllNotAssociation", targetNamespace = "http://service.yado.com/", className = "com.yado.cxf.FindAllNotAssociation")
    @ResponseWrapper(localName = "findAllNotAssociationResponse", targetNamespace = "http://service.yado.com/", className = "com.yado.cxf.FindAllNotAssociationResponse")
    public List<Customer> findAllNotAssociation();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.yado.cxf.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCustomerByTelephone", targetNamespace = "http://service.yado.com/", className = "com.yado.cxf.FindCustomerByTelephone")
    @ResponseWrapper(localName = "findCustomerByTelephoneResponse", targetNamespace = "http://service.yado.com/", className = "com.yado.cxf.FindCustomerByTelephoneResponse")
    public Customer findCustomerByTelephone(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "assigncustomerstodecidedzone", targetNamespace = "http://service.yado.com/", className = "com.yado.cxf.Assigncustomerstodecidedzone")
    @ResponseWrapper(localName = "assigncustomerstodecidedzoneResponse", targetNamespace = "http://service.yado.com/", className = "com.yado.cxf.AssigncustomerstodecidedzoneResponse")
    public void assigncustomerstodecidedzone(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<Integer> arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.yado.cxf.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllHadAssociation", targetNamespace = "http://service.yado.com/", className = "com.yado.cxf.FindAllHadAssociation")
    @ResponseWrapper(localName = "findAllHadAssociationResponse", targetNamespace = "http://service.yado.com/", className = "com.yado.cxf.FindAllHadAssociationResponse")
    public List<Customer> findAllHadAssociation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findDecidedzoneIdbyAddress", targetNamespace = "http://service.yado.com/", className = "com.yado.cxf.FindDecidedzoneIdbyAddress")
    @ResponseWrapper(localName = "findDecidedzoneIdbyAddressResponse", targetNamespace = "http://service.yado.com/", className = "com.yado.cxf.FindDecidedzoneIdbyAddressResponse")
    public String findDecidedzoneIdbyAddress(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.yado.cxf.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.yado.com/", className = "com.yado.cxf.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.yado.com/", className = "com.yado.cxf.FindAllResponse")
    public List<Customer> findAll();

}
